name: Docker 이미지 빌드 및 푸시 (Reusable)

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-version:
        required: true
        type: string
      dockerfile-path:
        description: '빌드할 Dockerfile의 (호출한 앱 리포지토리 내) 경로'
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.repository.full_name }}
          ref: ${{ github.event.ref }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB }}

      # 3. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile-path }}
          push: true
          
          tags: |
            ${{ inputs.image-name }}:${{ inputs.image-version }}
            ${{ inputs.image-name }}:latest
