name: Docker 이미지 빌드 및 푸시

# 1. 언제 실행할지 (트리거)
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-version:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      # 1. GitHub 레포지토리 코드를 가상 머신으로 복사
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

# 3. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: true
          
          tags: |
            ${{ inputs.image-name }}:${{ inputs.image-version }}
            ${{ inputs.image-name }}:latest
